# Generated by Django 3.1.5 on 2022-06-27 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0002_post_mainphoto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='mainphoto',
            new_name='post_image',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='postname',
            new_name='post_title',
        ),
    ]
